### ISSUE TITLE
Generated code doesn't compile when Obj-C inheritance hierarchy mixes methods and properties

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/native#1440] opened 2024-08-21 16:12 UTC
Property syntax was added to Objective-C well into the language's existence, and is only quasi-distinct from methods (unlike in Swift where the distinction matters at compile time); in practice, `foo.bar` and `[foo bar]` will both do the same thing if `bar` is declared as either a getter method or a property.

It looks like this conflation confuses ffigen. In a generation that included some Cocoa controls, I ended up with the following errors:
```
Class 'NSManagedObject' can't define method 'observationInfo' and have field 'NSObject.observationInfo' with the same name.
Try converting the method to a getter, or renaming the method to a name that doesn't conflict.
Class 'NSMatrix' can't define field 'selectedCell' and have method 'NSControl.selectedCell' with the same name.
Try converting the getter to a method, or renaming the field to a name that doesn't conflict.
Class 'NSBrowser' can't define field 'selectedCell' and have method 'NSControl.selectedCell' with the same name.
Try converting the getter to a method, or renaming the field to a name that doesn't conflict.
Class 'NSSliderCell' can't define method 'title' and have field 'NSCell.title' with the same name.
Try converting the method to a getter, or renaming the method to a name that doesn't conflict.
Class 'NSSliderCell' can't define method 'image' and have field 'NSCell.image' with the same name.
Try converting the method to a getter, or renaming the method to a name that doesn't conflict.
```

For `NSSliderCell`, for example, `title` and `image` are deprecated, so were never updated to property syntax, but the ancestor class (`NSCell`) versions were. This is fine in Obj-C, but the generated Dart is different.

**Comment by stuartmorgan** [comment] 2024-08-21 16:14
For reference, generated code for one of those examples:

`NSSliderCell.title`:
```dart
  objc.NSString title() {
    final _ret = _objc_msgSend_11(this.pointer, _sel_title);
    return objc.NSString.castFromPointer(_ret, retain: true, release: true);  }
```

`NSCell.title`:
```dart
  objc.NSString get title {
    final _ret = _objc_msgSend_11(this.pointer, _sel_title);
    return objc.NSString.castFromPointer(_ret, retain: true, release: true);  }
```

**Comment by liamappelbe** [comment] 2024-08-21 23:56
Dupe of https://github.com/dart-lang/native/issues/1220

**Closed by liamappelbe** 2024-08-21 23:56 UTC
Labels: package:ffigen
