### ISSUE TITLE
NDK crash in `libdartjni.so (GetApplicationContext+60)` when uploading to Play Store

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/native#1150] opened 2024-05-16 01:32 UTC
I am getting an NDK crash in `libdartjni.so (GetApplicationContext+60)` when I upload my APK to the Play Store.

![image](https://github.com/dart-lang/native/assets/811305/e5556d34-0e5b-4693-9747-3fbe60bc5789)

Any ideas?

**Comment by HosseinYousefi** [comment] 2024-05-16 10:16
* What version of `package:jni` are you using?
* Will this happen If you override the dependency to use the latest version of `package:jni`?
* Can you create a minimal reproducible repo that has this problem?

**Comment by lukehutch** [comment] 2024-05-16 10:32
> * What version of `package:jni` are you using?

`jni 0.7.3` -- required by `cronet_http 1.2.0` (which is the latest version currently).

> * Will this happen If you override the dependency to use the latest version of `package:jni`?

Do I do that in my project via `dependency_override`, or do I need to fork cronet_http to override the dependency there?

Do you know if `cronet_http` works with `jni 0.9.2`? I'm worried about causing runtime crashes by messing with dependency versions of NDK projects...

> * Can you create a minimal reproducible repo that has this problem?

I would have to create a whole new app consisting of just the cronet client, do all the Play Store setup for the app, and upload it for testing, to try to recreate the crash with the smallest amount of code possible (and I really can't afford the time to do something like that for a few weeks, because I'm about to launch my app).

It doesn't crash on my local device or emulator, but I don't know what would be different about the Play Store...

**Comment by lukehutch** [comment] 2024-05-16 10:34
Here is how I call into cronet, however... this would be close to my minimal repro case:

```dart
void main() async {
  // Set up better http clients on Android and iOS
  if (Platform.isAndroid) {
    final engine =
        CronetEngine.build(cacheMode: CacheMode.memory, cacheMaxSize: 1000000);
    runWithClient(_run, () => CronetClient.fromCronetEngine(engine));
  } else if (Platform.isIOS || Platform.isMacOS) {
    final config = URLSessionConfiguration.ephemeralSessionConfiguration()
      ..cache = URLCache.withCapacity(memoryCapacity: 1000000);
    runWithClient(_run, () => CupertinoClient.fromSessionConfiguration(config));
  } else {
    // Run with the default IOClient
    _run();
  }
}

void _run() async {
  // Must come first
  WidgetsFlutterBinding.ensureInitialized();

  // Call runApp from here...
}
```

**Comment by HosseinYousefi** [comment] 2024-05-16 10:36
Thanks for the quick reply.

> Do I do that in my project via `dependency_override`, or do I need to fork cronet_http to override the dependency there?
> 
> Do you know if `cronet_http` works with `jni 0.9.2`? I'm worried about causing runtime crashes by messing with dependency versions of NDK projects...

You can use this dependency:
```
cronet_http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: jni-0.9.2
      path: pkgs/cronet_http
```
I regenerated the bindings as well, so it will work just fine.

> It doesn't crash on my local device or emulator, but I don't know what would be different about the Play Store...

 I'll try to upload a cronet example app to play store to see if I get the same error.

**Comment by lukehutch** [comment] 2024-05-16 10:38
Thanks, awesome, that build saved me a lot of work! I'll replace this dep and see if it fixes the crash.

**Comment by lukehutch** [comment] 2024-05-16 10:41
While I have your attention -- is all of JNI deprecated in Android, or does `jni` just use something that is deprecated?:

> Note: /home/luke/.pub-cache/hosted/pub.dev/jni-0.9.2/android/src/main/java/com/github/dart_lang/jni/JniPlugin.java uses or overrides a deprecated API.

**Comment by HosseinYousefi** [comment] 2024-05-16 10:45
> Thanks, awesome, that build saved me a lot of work! I'll replace this dep and see if it fixes the crash.

The PR is here: https://github.com/dart-lang/http/pull/1198
Once `cronet_http: 1.2.1` gets released, you won't have to use a git dependency.



> While I have your attention -- is all of JNI deprecated in Android, or does `jni` just use something that is deprecated?:

Haha, I just had this conversation here: https://github.com/dart-lang/http/pull/1198#issuecomment-2114831051

It's not about JNI, it's something related to the way Flutter plugins work. I thought I have suppressed the warning, so users don't get confused by this message. However it seems that simply importing the deprecated class triggers the warning, so I should use the fully qualified name of the package instead of importing it.

You can safely ignore it, and I'll hide the warning in the next release of `package:jni`.

**Comment by HosseinYousefi** [comment] 2024-05-21 12:42
Any updates on this? `cronet_http: 1.2.1` is also released.

**Comment by lukehutch** [comment] 2024-05-21 21:58
Hi, I have been stuck on iOS build issues, so I haven't uploaded my Android app again to the Play store (and even back when I was uploading periodically, I only saw this specific crash once), but it's possible that one of the recent crash fixes in `jni` is the reason for the crash I experienced too, so it may be fixed. You can go ahead and close this if you want, and I'll comment on it again if I see the crash again.

You presumably know a lot about JNI already, but I figured I'd send you this link to a JNI project I created a while back. I found I had to very carefully check every incoming parameter (including ensuring that the user is not trying to call a static method in a non-static way or vice versa, etc.), and the `thrown` status after every JNI call, to avoid crashes. It's a very finicky API. There may be some safety mechanisms that you can see in this code that would be useful for your `jni` package too, to protect against future possibilities of crashes.

https://github.com/toolfactory/narcissus/blob/main/src/main/c/narcissus.c

**Comment by lukehutch** [comment] 2024-05-30 06:27
Hi @HosseinYousefi -- with latest `jni`, I am now getting the same exact crash on Android:

https://github.com/flutter/flutter/issues/149229

Can you please re-open this issue?

It seems that `jniEnv` is not initialized when `GetApplicationContext` is called:

https://github.com/dart-lang/native/blob/1549dc850a7498954d68e5cdb5583789c37165a4/pkgs/jni/src/dartjni.c#L116

**Comment by lukehutch** [comment] 2024-06-05 09:31
@HosseinYousefi Any ideas how to go about debugging what is going on here?

**Comment by HosseinYousefi** [comment] 2024-06-05 09:36
We recently had an issue regarding 32-bit devices, can you check if the devices with the error happen to be 32-bit?

I have a PR to fix cronet, the new version will be published soon: https://github.com/dart-lang/http/pull/1225

**Comment by lukehutch** [comment] 2024-06-05 09:43
@HosseinYousefi No, it's a Pixel 7 Pro, so it's a 64-bit device.

I looked through how the plugin is registered, and I can't see how `GetApplicationContext` could possibly be called before `initializeJni` is called. So potentially `jniEnv` is being set back to null somehow?

**Comment by lukehutch** [comment] 2024-06-05 16:45
Unfortunately I have only seen this on release and profile builds, and I have not been able to symbolize the stacktraces. But it's crashing in `GetApplicationContext()` with a null reference, and there's only one way that can happen.

It is sporadic, and right now I can't replicate it, but it keeps resurfacing.

**Comment by lukehutch** [comment] 2024-06-06 21:36
> One theory: we have not been calling `detach_thread`, maybe that causes problems? My fix for this is already landed here: #1163. You can override the `jni` dependency to the main branch of this repo to see if that fixes it.

Your fix for #557 doesn't zero-out `jniEnv` on `deinit`, but even if it did, that would not solve this but potentially *introduce* a race condition (if another thread is trying to call `GetApplicationContext` as the JNI-attached thread is shutting down).

However the note in #557 may have identified the problem:

> To me it seems we are lazily attaching to the current thread and caching the result in a thread_local `JNIEnv*`.

So potentially `GetApplicationContext` is being called before the lazy initializer is being called? What triggers the lazy initializer? Can `GetApplicationContext` (and other methods) be made to trigger it if necessary?

**Comment by lukehutch** [comment] 2024-06-07 01:17
I just checked the reproducibility, and this crash has occurred 100% of the time in the testing phase of five different build uploads to Google Play.

Locally, I used to be able to reproduce this in Profile builds, but that somehow spontaneously fixed itself without any code changes, after clearing build files and re-building.

This is a total showstopper for my app, because I can't even get through Play Store app review with the app crashing on load. I may have to launch without cronet.

**Comment by lukehutch** [comment] 2024-06-07 05:52
> `jniEnv` is thread local. So it will be null on new threads. However we always run `attach_thread()` which uses the cached global `jvm` to fill it again, so it's odd to see that it's null.

If you're just making a thread-local copy of a single global `jniEnv` instance every time you instantiate a new thread, then why is this even a thread-local reference? Just use the global entrance, it's safer, and it would solve the race condition issue, at least in this particular case.

**Comment by lukehutch** [comment] 2024-06-20 18:39
@HosseinYousefi I created the Cronet bug and test project as requested: https://github.com/dart-lang/http/issues/1241

This test project doesn't crash on my machine, but the release build does lock up.

**Comment by HosseinYousefi** [comment] 2024-06-25 11:13
> @HosseinYousefi I created the Cronet bug and test project as requested: [dart-lang/http#1241](https://github.com/dart-lang/http/issues/1241)
> 
> This test project doesn't crash on my machine, but the release build does lock up.

I can't reproduce the locking up of release build.

**Comment by lukehutch** [comment] 2024-06-27 19:23
@HosseinYousefi Is there anything else I can do to debug this?

**Comment by HosseinYousefi** [comment] 2024-06-27 19:40
> @HosseinYousefi Is there anything else I can do to debug this?

Well, as you cannot reproduce it on your machine, and I don't seem to be able to reproduce it on mine, there is nothing we can do to fix it this way. 

You say that the play store's checks fail. Can you share a minimal app that fails the play store checks? This way at least I can create a play store account and iterate to see what makes it fail. 

You are the only person reporting this bug, so I highly doubt the example is going to be as simple as just initializing cronet.

**Comment by lukehutch** [comment] 2024-06-27 20:34
> Well, as you cannot reproduce it on your machine

I am able to reproduce the lock-up issue on my machine with the minimal repro code that I shared. That code just does not crash in the same way as I originally reported -- but it should not lock up, so this is still worth looking into. Any tips for how to debug what is happening on my machine with that example?

> You are the only person reporting this bug, so I highly doubt the example is going to be as simple as just initializing cronet.

The crash happens before Flutter starts, and the only thing that my app does after initializing cronet is to start Flutter. I looked to see if any other plugins use JNI, and there aren't any. Possibly this is a memory corruption bug.

**Comment by HosseinYousefi** [comment] 2024-06-27 20:54
> I am able to reproduce the lock-up issue on my machine with the minimal repro code that I shared. That code just does not crash in the same way as I originally reported -- but it should not lock up, so this is still worth looking into. Any tips for how to debug what is happening on my machine with that example?

These are probably separate issues, I'm talking about the original crash. The lock-up issue might be a cronet specific one.

In any case these are some steps you can take:

What is the output of your `flutter doctor`?
Does this only happen with `cronet_http` as a dependency? 
What about having only `jni` as a dependency and doing something simple, like `print('hello'.toJString());`, does this fail too?
Have you tried depending on the master branch of cronet? Make sure you do `flutter pub upgrade` and `flutter clean` before rebuilding.

**Comment by HosseinYousefi** [comment] 2024-06-27 21:30
I'm now pretty sure that the problem is not jni-related. Closing this issue. Let's continue any further discussions in the http thread.

**Closed by HosseinYousefi** 2024-06-27 21:30 UTC
Labels: package:jnigen, package:jni
