### ISSUE TITLE
[FFI] [WASM] flutter build error

### ISSUE THREAD

**Issue by zs-dima** [dart-lang/native#1210] opened 2024-06-13 20:46 UTC
flutter build web --wasm

Leads to the Errors
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/allocation.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/utf16.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/utf8.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/arena.dart:8:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^
* * *

please, take a look 
https://dart.dev/interop/js-interop
https://dart.dev/interop/js-interop/package-web

**Comment by dcharkes** [comment] 2024-06-14 06:41
cc @mkustermann

**Comment by mkustermann** [comment] 2024-06-14 13:10
Dart2wasm doesn't support `dart:ffi` at the moment (just as `dart2js` - which is the default for `flutter build web`). There has been a bug in the compiler that evaluated conditional imports (where condition is based on `dart.library.ffi`) incorrectly. This bug has been fixed and it has rolled up to flutter main/master branch (but the fix isn't available in flutter stable yet, as stable hot fix releases are slower than usual atm)

@zs-dima Could you try flutter master/main channel?

Closing this issue as fixed. Please re-open or file a new issue (with reproduction instructions!!!) if you continue to see this issue.

**Closed by mkustermann** 2024-06-14 13:10 UTC
Labels: package:ffigen

**Comment by zs-dima** [comment] 2024-06-15 18:35
@mkustermann @dcharkes 
master/main channel still has this issue:
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/allocation.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/utf16.dart:5:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/utf8.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
/home/flutter/.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/src/arena.dart:8:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi';
^

**Comment by mkustermann** [comment] 2024-06-17 08:00
>  master/main channel still has this issue:

Then it most likely is a sign that you're using packages directly or indirectly that import `package:ffi` (which imports `dart:ffi` internally) - which we don't support in web compilers atm. The conditional import on `dart.library.ffi` is available on flutter's main/master channel, so that has been fixed.

There may be some packages that you use that haven't been upgraded to the new JS interop (see [dart.dev/interop/js-interop](https://dart.dev/interop/js-interop)). One possibility I can see is that you're directly/indirectly using a package that uses a conditional import with `dart.library.html` as condition. If so, that code has to be migrated to new static interop for it to work with all our web compilers. @zs-dima Could you investigate what the import graph looks like and if this is the case?

**Comment by AlexBacich** [comment] 2024-07-03 14:32
I got this error when was trying to use Sentry: 
`sentry_flutter: ^8.3.0`

After switching to the branch with web support imports to FFI were gone and the issue gone too: 
```
  sentry_flutter: 
    git:
      url: https://github.com/getsentry/sentry-dart.git
      ref: 3216f42
      path: flutter
```

So @zs-dima you should really see which other libraries throw you errors and fix them first.
