### ISSUE TITLE
Dealing with Tasks in jnigen

### ISSUE THREAD

**Issue by Marco4763** [dart-lang/native#609] opened 2023-06-15 16:41 UTC
I wrote this [article](https://medium.com/@marcoedomingos/the-ultimate-showdown-methodchannel-vs-d83135f2392d) about jnigen with what I could glean from the test I did and in the test I came across a function which returns a task, if I had to handle a task in Kotlin it would be something like this:
```
scanner.startScan()
    .addOnSuccessListener { barcode ->
        // Task completed successfully
    }
    .addOnCanceledListener {
        // Task canceled
    }
    .addOnFailureListener { e ->
        // Task failed with an exception
    }
```

Unfortunately I was not able to do the treatment in the same way in Dart, in the end, I managed to get around it this way:
```
final task = scanner.startScan();
while(!task.isComplete()){
  await Future.delayed(const Duration(milliseconds: 500));
}

setState(() {
  scanned = task.getResult().getRawValue().toDartString();
});
```

But I don't believe this is the best approach, is there another way to handle this?

**Comment by Marco4763** [comment] 2023-11-24 08:56
Hi @HosseinYousefi, it worked for me, this is the implementation I did:

```
      final scanner = GmsBarcodeScanning.getClient(JObject.fromRef(Jni.getCachedApplicationContext()));
      final scanResult = scanner.startScan().TResult;

      scanner.startScan().addOnSuccessListener(
          OnSuccessListener.implement($OnSuccessListenerImpl(
            TResult: scanResult,
            onSuccess: (value) {
              setState(() {
                result = value.getRawValue().toDartString();
              });
            },
          ))).addOnCanceledListener(OnCanceledListener.implement($OnCanceledListenerImpl(
        onCanceled: () {
          setState(() {
            result = "Cancelado";
          });
        },
      ))).addOnFailureListener(
          OnFailureListener.implement($OnFailureListenerImpl(
            onFailure: (value) {
              setState(() {
                result = "Falha";
              });
            },
          )));
```
          


The only problem is that this way it end up calling the scan method twice, so, after a little creativity, this was the final result:

 ``` 
      final scanner = GmsBarcodeScanning.getClient(JObject.fromRef(Jni.getCachedApplicationContext()));
      
      scanner.startScan()
        ..addOn<OnSuccessListener<Barcode>>((barcode) => setState(() => result = barcode.getRawValue().toDartString()))
        ..addOn<OnCanceledListener>((_) => setState(() => result = "Cancelado"))
        ..addOn<OnFailureListener>((e) => setState(() => result = "Falha $e"));    
 ```
 
This way, not only does it look similar to the native implementation, but it also calls the scan method just once and handles all possible outcomes.

**Comment by HosseinYousefi** [comment] 2023-11-27 11:38
> ```
>       final scanResult = scanner.startScan().TResult;
> 
>       scanner.startScan().addOnSuccessListener( 
> ```

Well, you're calling `startScan()` twice. You can call it once and then add the listeners, get the result, etc.

```dart
final task = scanner.startScan();
final result = task.TResult;
task.addOnSuccessListener(...);
// ...
```

Overall, I think the issue is resolved, so I'll close this!

**Closed by HosseinYousefi** 2023-11-27 11:38 UTC
Labels: package:jnigen, package:jni

**Comment by orestesgaolin** [comment] 2025-02-10 11:40
I read this issue few times so perhaps it may be worth sharing with future readers how I ended up solving a similar but slightly different use case of [Task from Google Play Services ](https://developers.google.com/android/reference/com/google/android/gms/tasks/Task.html)

The `onSuccessListener` returns generic Task<TResult> and passes the result to the callback.

![Image](https://github.com/user-attachments/assets/166c5161-621b-43cf-9ff3-f042db3c1570)

It took me a while to figure out that I need to pass `ClassName.type` as the `TResult` argument to the `$OnSuccessListener<AppUpdateInfo>`


```dart
    appInfoTask?.addOnSuccessListener(
      OnSuccessListener.implement(
        $OnSuccessListener<AppUpdateInfo>(
          onSuccess$async: true,
          TResult: AppUpdateInfo.type,
          onSuccess: (result) {
            setState(() {
              appUpdateInfo = result;
            });
          },
        ),
      ),
    );
```

[Code in context](https://github.com/orestesgaolin/native_interop_presentation/blob/5515bfe6322de557ca4f80458422b546a51b4387/appupdate/example/lib/main.dart#L44-L56)
