### ISSUE TITLE
Unclear how (if even possible?) to filter Obj-C categories

### ISSUE THREAD

**Issue by stuartmorgan** [dart-lang/native#1439] opened 2024-08-21 15:58 UTC
I added what I expected to be a small additional API surface to my `exclude-all-by-default: true` Obj-C ffigen set, and then re-ran and was seeing a ton of unexpected new Cocoa UI classes. I picked one and tried to trace why it was included via verbose logging, and it looks like the problem is that I am now using `NSView`, and every type used in *every category on `NSView`* is now being considered a transitive inclusion.

Arguably this is just a special case of needing method filtering, but I think it's worth filing separately because this is pretty unexpected behavior; if I use an extremely core class, I do not expect to get every highly use-case-specific extension to that class that's reachable anywhere in the SDK when I'm using default-exclude. I can see the argument for this behavior, but I think the NSView case is a potential argument against default-including categories for any included type. And even if we do want to default-include them, it should be possible to exclude them by category rather than by method.

**Comment by liamappelbe** [comment] 2024-08-21 23:58
Dupe of https://github.com/dart-lang/native/issues/271

**Closed by liamappelbe** 2024-08-21 23:58 UTC
Labels: package:ffigen
