### ISSUE TITLE
[native_toolchain_c] Expose APIs from `tool` and `native_toolchain`

### ISSUE THREAD

**Issue by blaugold** [dart-lang/native#1795] opened 2024-12-09 21:30 UTC
I'm working on a [`MesonBuilder`](https://github.com/blaugold/native/blob/0585d40ae7180a5f45fc96acca71409b0b3cd133/pkgs/native_toolchain_c/lib/src/meson_builder/meson_builder.dart) that wraps the [Meson build system](https://mesonbuild.com/).

In its WIP state, it lives in `native_toolchain_c` because it needs the same C toolchain discovery tools as `CBuilder`.  Wrappers around other build systems (e.g CMake) will have similar needs.

Could the APIs from `tool` and `native_toolchain`, as well as `CompilerResolver`, `runProcess` and `environmentFromBatchFile` be mad public APIs?

**Comment by dcharkes** [comment] 2024-12-10 08:48
> I'm working on a [`MesonBuilder`](https://github.com/blaugold/native/blob/0585d40ae7180a5f45fc96acca71409b0b3cd133/pkgs/native_toolchain_c/lib/src/meson_builder/meson_builder.dart) that wraps the [Meson build system](https://mesonbuild.com/).

Cool! We can have a `package:native_toolchain_meson`!

> Could the APIs from `tool` and `native_toolchain`, as well as `CompilerResolver`, `runProcess` and `environmentFromBatchFile` be mad public APIs?

Yes we should.

So far I hadn't done it yet because there's still a bunch of things we could improve. For example:

* [ ] https://github.com/dart-lang/native/issues/857
* [ ] https://github.com/dart-lang/native/issues/20
* [ ] https://github.com/dart-lang/native/issues/19

I haven't prioritized making the tools a nice API, because it's not public right now.

Before we make them public APIs, it would be good to think about what a good public API would be. You could sketch out the API that you would want to use from your package and that you think will not require breaking changes too quickly. (Some breaking changes in the future is fine, we are still 0.x on this package.) And then we can ask the authors of `native_toolchain_go` and `native_toolchain_rust` for feedback if they would use it.

I'd probably expose these as `package:native_toolchain_c/tool.dart` instead of in the main export. (Maybe at some point the logic related to discovering toolchains that is not tied to C toolchains specifically should be moved into a separate package, but let's keep it in one place for now.)

`environmentFromBatchFile` is already public and should probably be moved there instead.

`runProcess` has nothing to do with native toolchains, so I'm a bit hesitant to export it. (In fact, it's copy pasted in the packages here.)

This issue is a duplicate of:

* https://github.com/dart-lang/native/issues/856

Let's continue the discussion there.

**Closed by dcharkes** 2024-12-10 08:48 UTC
Labels: package:native_toolchain_c

**Comment by blaugold** [comment] 2024-12-10 08:54
Ah, I didn't see that issue! Sorry for the noise. 🙈
