### ISSUE TITLE
We are getting an issue with this package

### ISSUE THREAD

**Issue by kostricanitechnology** [dart-lang/native#945] opened 2024-01-19 15:05 UTC
Hello, 
When I try to build the app for iOS I am getting this error 

Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/ffi-2.1.2/lib/ffi.dart:1:1: Error: The specified language version is too high. The highest supported language version is
3.2.

Below is my flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.0 23A344 darwin-arm64, locale en-AL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by dcharkes** [comment] 2024-01-19 15:52
What does your `pubspec.yaml` look like?

Dart 3.3 only has a beta release, and the package sdk constraint is set to deal with that. So pub should only resolve to ffi 2.1.1, not to ffi 2.1.2.

Possibly a duplicate of:

* https://github.com/dart-archive/ffi/issues/231

**Comment by kostricanitechnology** [comment] 2024-01-19 15:54
Thanks for your response. What exactly you want to see on the pubspec?

I tried also the version ffi 2.1.1 but got same issue

**Comment by dcharkes** [comment] 2024-01-19 16:02
> Thanks for your response. What exactly you want to see on the pubspec?
> 
> I tried also the version ffi 2.1.1 but got same issue

Oops, I meant 2.1.0. https://pub.dev/packages/ffi/versions 2.2.1 also needs Dart 3.3 beta. Sorry for the confusion.

**Comment by kostricanitechnology** [comment] 2024-01-19 16:03
Also tried the 2.1.0 and same error.

**Comment by dcharkes** [comment] 2024-01-19 16:04
> Also tried the 2.1.0 and same error.

What does your pubspec look like?

**Comment by kostricanitechnology** [comment] 2024-01-19 16:06
There are a lot of things I have on pubspec, what exactly you want to see so I can send.

**Comment by dcharkes** [comment] 2024-01-19 16:09
> The highest supported language version is 3.2.

Are you sure that is the error message you get with `ffi: 2.1.0`? Version 2.1.0 has an SDK constraint of 3.0 https://github.com/dart-archive/ffi/blob/c926657618443ff4821411ede01684096b503f84/pubspec.yaml#L12 why would package ffi be resolved to version 2.1.1 or 2.1.2 ?

> There are a lot of things I have on pubspec, what exactly you want to see so I can send.

Everything: I don't know how else to trouble-shoot why `package:ffi` is not being resolved to 2.1.0 even though you've specified 2.1.0.

**Comment by kostricanitechnology** [comment] 2024-01-24 09:13
Hello,

On flutter pub get --verbose I do not see this package, looks like it is not installed.

**Comment by kostricanitechnology** [comment] 2024-01-24 19:47
seems that the issue was with the package url_protocol: ^1.0.0. `I removed that and it works now.

Thanks for the support

**Closed** 2024-01-24 19:47 UTC
Labels: package:ffigen
